### ISSUE TITLE
TypeError: Cannot read property 'qqfile' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/notes#65]
```
TypeError: Cannot read property 'qqfile' of undefined
    at module.exports.addFile (/usr/local/cozy/apps/notes/server/controllers/notes.js:231:19)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/index.js:340:14)
    at paramCallback (/usr/local/cozy/apps/notes/node_modules/americano/node_modules/express/lib/router/index.js:391:21)
    at /usr/local/cozy/apps/notes/server/controllers/notes.js:41:12
    at Function.<anonymous> (/usr/local/cozy/apps/notes/node_modules/americano-cozy/node_modules/jugglingdb/lib/model.js:447:9)
```

**Comment by clochix** [comment]
Closing, this has been fixed for some time now.
